#!/usr/bin/env python3
"""Generate a formatted research report from findings.

This script takes research findings from stdin or a file and produces
a formatted markdown report with proper citations and structure.

Usage:
    python generate-report.py [--input findings.md] [--output report.md]
    echo "findings" | python generate-report.py
"""

import argparse
import sys
from datetime import datetime


def generate_report(findings: str, topic: str = "Research") -> str:
    """Generate a formatted research report.
    
    Args:
        findings: Raw research findings text
        topic: The research topic/title
        
    Returns:
        Formatted markdown report
    """
    date = datetime.now().strftime("%Y-%m-%d")
    
    report = f"""# Research Report: {topic}

**Generated:** {date}

---

## Summary

{findings}

---

## Methodology

This research was conducted using web search tools to gather information from
multiple sources. Sources were evaluated for credibility and recency.

---

*Generated by AG3NT web-research skill*
"""
    return report


def main():
    parser = argparse.ArgumentParser(description="Generate research report")
    parser.add_argument("--input", "-i", help="Input findings file")
    parser.add_argument("--output", "-o", help="Output report file")
    parser.add_argument("--topic", "-t", default="Research", help="Research topic")
    args = parser.parse_args()
    
    # Read input
    if args.input:
        with open(args.input, "r", encoding="utf-8") as f:
            findings = f.read()
    else:
        findings = sys.stdin.read()
    
    # Generate report
    report = generate_report(findings, args.topic)
    
    # Write output
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(report)
        print(f"Report saved to {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()

